Fix two build warnings for unused functions
Reonu/HackerSM64 pull request #142
Opened 2021-12-14 04:01 UTC by Arceveti

2021-12-14 12:21 UTC, thecozies commented on src/goddard/renderer.c
> +    s32 trackerNum;            // memtracker id and/or i
bring the refactor to base decomp

2021-12-14 12:21 UTC, thecozies requested changes
base decomp could use the refactors

2021-12-15 21:02 UTC, thecozies approved these changes
yayyyyyy

2021-12-15 21:07 UTC, Mr-Wiseguy commented on tools/slienc.c
> +	size_t fread_result = fread(bz, 1, insize, fp);
I'd argue this isn't the best way to fix the warning, but since it's tool code and not game code I don't think it matters too much.

2021-12-15 21:07 UTC, Mr-Wiseguy approved these changes

2021-12-15 21:19 UTC, merged