Sdata
Reonu/HackerSM64 pull request #453
Opened 2022-07-13 10:46 UTC by FazanaJ

2022-07-13 20:57 UTC, arthurtilly commented
this pr FUCKING SUCKS!

2022-07-13 21:53 UTC, Reonu commented
bruh

2022-08-08 00:30 UTC, Reonu commented
can we merge this @thecozies @arthurtilly

2022-08-08 02:37 UTC, arthurtilly commented
HOW SHOULD I KNOW

2022-08-09 23:40 UTC, gheskett requested changes

2022-08-09 23:40 UTC, gheskett commented on Makefile
> +  $(BUILD_DIR)/levels/%.o:           CFLAGS += -G 0
I think this is supposed to be actors, not levels

2022-11-09 09:21 UTC, Reonu commented
closing this PR since apparently the concensus is that it won't get merged, but feel free to re-open it if that changes

2022-11-09 10:51 UTC, Reonu commented
My bad, apparently there's a plan to fix this

2022-11-09 19:47 UTC, gheskett commented
Can we close this PR a third time? The answer might surprise you!

2024-11-03 03:09 UTC, gheskett commented
As of HackerSM64 2.4, this PR has been outdated in favor of this branch: https://github.com/HackerN64/HackerSM64/tree/develop/2.1.0-sdata

No new PR will be opened for this until it is decided to be worth merging into HackerSM64 (if that ever happens).

2024-11-03 03:09 UTC, closed without merging