Objects rendering on F3DLX2.Rej
Reonu/HackerSM64 pull request #56
Opened 2021-09-16 17:02 UTC by FazanaJ

2021-09-16 17:18 UTC, Reonu commented
Does this basically mean that tris from objects that are outside of the screen get rejected? What makes that different from normal object culling, exactly?

2021-09-16 17:26 UTC, FazanaJ commented
It's faster, and supports a higher vertex buffer

2021-09-16 21:10 UTC, Reonu approved these changes
this looks epic to me but needs to be reviewed by someone smarter than me

@someone2639 @Arceveti @thecozies

2021-09-16 21:23 UTC, someone2639 requested changes
thats all from me otherwise if it works its epic

2021-09-16 21:23 UTC, someone2639 commented on src/engine/behavior_script.c
> +    UNUSED u32 unused;
remove the unused xd

2021-09-16 21:23 UTC, someone2639 commented on src/engine/level_script.c
> +    init_rcp(1);
enum this so it's clear what 1 represents

2021-09-16 21:23 UTC, someone2639 commented on src/engine/level_script.c
> +    init_rcp(1);
even if it was `TRUE` it would still be unclear imo, maybe a ```
enum ZBModes {
NO_RESET_ZB = 0,
RESET_ZB,
};``` would work

2021-09-16 21:23 UTC, someone2639 commented on src/game/game_init.c
> +
newline

2021-09-16 21:23 UTC, someone2639 commented on src/game/rendering_graph_node.c
> +    init_rcp(0);
same here

2021-09-16 22:17 UTC, FazanaJ commented
Functionally it's pretty good. I've probably forgotten a few objects to whitelist, but it's easy to add more. Just give it OBJ_FLAG_UCODE_LARGE and make sure it's an OR_LONG instead of an OR_INT in the behaviour script to add more 😎

2021-09-17 12:27 UTC, farisawan-2000 approved these changes
a

2021-09-17 12:29 UTC, merged