Add Arthurtilly to the CODEOWNERS file
Reonu/HackerSM64 pull request #821
Opened 2024-08-17 13:49 UTC by Reonu

2024-08-17 13:50 UTC, arthurtilly requested changes
dont trust this guy

2024-08-17 14:14 UTC, gheskett commented
I'll come back to this later when I have time, but I feel like there's gotta be a way to make the CODEOWNERS not only look at the bottom entry.

2024-08-18 01:02 UTC, gheskett requested changes

2024-08-18 01:02 UTC, gheskett commented on CODEOWNERS
> +*       @arthurtilly
Try this actually. I think the issue is that we're re-establishing a global CODEOWNER every time, but by adding them as part of the same line, it should allow everyone to share the role of a global CODEOWNER...I think.

```suggestion
*       @Reonu @thecozies @gheskett @arthurtilly
```

2024-08-18 14:04 UTC, gheskett approved these changes
This is now ready to go. (Please squash this one.)

2024-08-18 15:08 UTC, Reonu commented
Closing since Arthur doesn't trust that guy

2024-09-05 03:22 UTC, arthurtilly approved these changes

2024-09-05 03:24 UTC, merged