Add new GZIP DEFLATE decompressor/compressor
Reonu/HackerSM64 pull request #850
Opened 2024-12-29 12:11 UTC by aglab2

Replaced GZIP DEFLATE decompression algorithm from [libdeflate](https://github.com/ebiggers/libdeflate) instead of ancient libz implementation. It roughly doubles decompression performance while being smaller.

![image](https://github.com/user-attachments/assets/bd4c9322-b818-4270-9ce1-e1e7232fcfe8)
![image](https://github.com/user-attachments/assets/06a44faf-1b11-4438-8453-f07c4e67d41f)

File sizes:
6869784 sm64_deflate_new.z64
6876360 sm64_deflate_old.z64

2025-01-30 01:35 UTC, arthurtilly approved these changes

2025-02-16 08:20 UTC, gheskett requested changes
Any reason we're now unconditionally adding gzip to the repo, even when using a non-gzip compression format by default?

2025-02-16 08:20 UTC, gheskett commented on src/boot/memory.c
> +#endif
Is this forgotten debug code?

2025-02-16 08:22 UTC, aglab2 commented
> Any reason we're now unconditionally adding gzip to the builds, even when using a non-gzip compression format by default?

I suggest compression code massacre to remove all unrelated stuff. We build lots of tools for other compression algos as well.

2025-05-13 13:21 UTC, arthurtilly commented
@gheskett What is the requested change here

2025-05-13 13:54 UTC, gheskett commented
> @gheskett What is the requested change here

The funny debug snippet and merge conflict

2025-06-21 01:16 UTC, aglab2 commented on src/boot/memory.c
> +#endif
Removed the useless code.

2025-06-21 01:17 UTC, aglab2 commented
Merge conflicts were fixed, ready for another round of review

2025-06-21 07:09 UTC, gheskett approved these changes

2025-07-02 04:37 UTC, merged

2025-07-23 19:45 UTC, KazeEmanuar reviewed
ok